[package]
name = "slh-dsa-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "FIPS 205 (draft): Module-Lattice-Based Digital Signature Standard"
repository = "https://github.com/integritychain/slh-dsa-rs"
rust-version = "1.73"


[dependencies]
