#include <stdio.h>
#include <string.h>
#include <fips205.h>

#define PASTE3(a, b, c) a##b##c
#define SLH_I(prefix, name) PASTE3(prefix, _, name)
#define SLH(name) SLH_I(PFX, name)

int main(void) {
  SLH(public_key) pub;
  SLH(private_key) priv;
  SLH(public_key) pub_2;
  SLH(private_key) priv_2;
  SLH(public_key) otherpub;
  SLH(signature) sig;
  SLH(signature) sig_2;
  slh_dsa_keygen_seed seed;
  slh_dsa_err err;

  const uint8_t msg[] = "wfwfwf";
  const uint8_t ctx[] = "testing";
  const uint8_t badmsg[] = "ffffff";
  const uint8_t badctx[] = "badctx";
  const size_t msglen = 6;
  const size_t ctxlen = 7;
  const size_t badctxlen = 6;
  const size_t badmsglen = 6;

  memset(&seed, 0, sizeof(seed));

  if (SLH(keygen_from_seed)(&seed, &pub, &priv))
    return 1;
  if (SLH(keygen_from_seed)(&seed, &pub_2, &priv_2))
    return 1;
  if (memcmp(&pub, &pub_2, sizeof(pub))) {
    fprintf(stderr, "public keys generated by seed did not match\n");
    return 5;
  }
  if (memcmp(&priv, &priv_2, sizeof(priv))) {
    fprintf(stderr, "private keys generated by seed did not match\n");
    return 6;
  }

  if (SLH(keygen)(&pub, &priv))
    return 1;

  if ((err = SLH(get_public_key)(&priv, &otherpub))) {
    fprintf(stderr, "failed to extract public key (err: %d)\n", err);
    return 9;
  }
  if (memcmp(&pub, &otherpub, sizeof(pub))) {
    fprintf(stderr, "get_public_key() output failed to match keygen() output\n");
    return 10;
  }

  if (SLH(sign)(&priv, msg, msglen, ctx, ctxlen, &sig))
    return 2;
  if (SLH(sign)(&priv, msg, msglen, ctx, ctxlen, &sig_2))
    return 2;
  if (!memcmp(&sig, &sig_2, sizeof(sig))) {
    fprintf(stderr, "Hedged signatures match; they should use entropy\n");
    return 6;
  }
  if (SLH(verify)(&pub, &sig, msg, msglen, ctx, ctxlen)) {
    fprintf(stderr, "verify sig failed!\n");
    return 7;
  }
  if (SLH(verify)(&pub, &sig_2, msg, msglen, ctx, ctxlen)) {
    fprintf(stderr, "verify sig_2 failed!\n");
    return 7;
  }

  if (SLH(sign_deterministic)(&priv, msg, msglen, ctx, ctxlen, &sig))
    return 2;
  if (SLH(sign_deterministic)(&priv, msg, msglen, ctx, ctxlen, &sig_2))
    return 2;
  if (memcmp(&sig, &sig_2, sizeof(sig))) {
    fprintf(stderr, "deterministic signatures did not match\n");
    return 8;
  }
  if (SLH(verify)(&pub, &sig, msg, msglen, ctx, ctxlen)) {
    fprintf(stderr, "verify deterministic sig failed!\n");
    return 7;
  }

  if (!SLH(keygen)(&pub, NULL)) {
    fprintf(stderr, "keygen should have failed with NULL private key\n");
    return 1;
  }
  if (!SLH(keygen)(NULL, &priv)) {
    fprintf(stderr, "keygen should have failed with NULL public key\n");
    return 1;
  }
  if (!SLH(keygen)(NULL, NULL)) {
    fprintf(stderr, "keygen should have failed with NULL keys\n");
    return 1;
  }

  if (!SLH(sign)(NULL, msg, msglen, ctx, ctxlen, &sig_2)) {
    fprintf(stderr, "sign should have failed with NULL priv\n");
    return 1;
  }
  if (!SLH(sign)(&priv, NULL, msglen, ctx, ctxlen, &sig_2)) {
    fprintf(stderr, "sign should have failed with NULL msg\n");
    return 1;
  }
  if (!SLH(sign)(&priv, msg, msglen, NULL, ctxlen, &sig_2)) {
    fprintf(stderr, "sign should have failed with NULL ctx\n");
    return 1;
  }
  if (!SLH(sign)(&priv, msg, msglen, ctx, ctxlen, NULL)) {
    fprintf(stderr, "sign should have failed with NULL sig_out\n");
    return 1;
  }
  if (SLH(sign)(&priv, NULL, 0, ctx, ctxlen, &sig_2)) {
    fprintf(stderr, "sign should have succeeded with NULL and empty msg\n");
    return 1;
  }
  if (SLH(sign)(&priv, msg, msglen, NULL, 0, &sig_2)) {
    fprintf(stderr, "sign should have succeeded with NULL and empty ctx\n");
    return 1;
  }

  if ((err = SLH(verify)(&pub, &sig, msg, msglen, ctx, ctxlen))) {
    fprintf(stderr, "verify should have succeeded! (got %d)\n", err);
    return 3;
  }
  if (!SLH(verify)(&pub, &sig, msg, msglen, badctx, badctxlen)) {
    fprintf(stderr, "verify should have failed if the context changed\n");
    return 4;
  }
  if (!SLH(verify)(&pub, &sig, badmsg, badmsglen, ctx, ctxlen)) {
    fprintf(stderr, "verify should have failed if the message changed\n");
    return 5;
  }
  sig.data[3]++;
  if (!SLH(verify)(&pub, &sig, msg, msglen, ctx, ctxlen)) {
    fprintf(stderr, "verify should have failed if the signature was tampered with\n");
    return 6;
  }

  printf("ok\n");
  return 0;
}
